### ISSUE TITLE
is there any documentation for this project?

### ISSUE THREAD

**Issue by swissChili** [KaidemonLP/Open-Fortress-Source#5]
The readme is empty as is the wiki, are there any plans for formal documentation, at least a brief introduction to the source engine would be nice.

**Comment by AlphaBlaster** [comment]
The wiki doesn't belong to us, it was created by some random idiot who's not a developer.

**Comment by AlphaBlaster** [comment]
The wiki doesn't belong to us. As for a proper readme and other documentation, those may be added when the project is complete as it is currently still in development.

**Comment by swissChili** [comment]
I meant the github wiki btw, but alright
